<?php
/**
 * CpeFilterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SUNAT API
 *
 * CONSULTA INTEGRADA DE COMPROBANTE DE PAGO.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: giansalex@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * CpeFilterTest Class Doc Comment
 *
 * @category    Class
 * @description CpeFilter
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CpeFilterTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CpeFilter"
     */
    public function testCpeFilter()
    {
    }

    /**
     * Test attribute "num_ruc"
     */
    public function testPropertyNumRuc()
    {
    }

    /**
     * Test attribute "cod_comp"
     */
    public function testPropertyCodComp()
    {
    }

    /**
     * Test attribute "numero_serie"
     */
    public function testPropertyNumeroSerie()
    {
    }

    /**
     * Test attribute "numero"
     */
    public function testPropertyNumero()
    {
    }

    /**
     * Test attribute "fecha_emision"
     */
    public function testPropertyFechaEmision()
    {
    }

    /**
     * Test attribute "monto"
     */
    public function testPropertyMonto()
    {
    }
}
